name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux, X64, test-1]

    steps:
      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          deployment_mode: docker-swarm
          args: my_applicaion
