name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

   runs-on: [self-hosted, linux, X64, test-1]

   steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nginx:$(date +%s)
    - name: Compose
      run: docker build -t nginx --no-cache .
