name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

   runs-on: [self-hosted, linux, X64, test-1]

   steps:
    - uses: actions/checkout@v3
    - name: Compose
      run: docker build -t nginx .
