name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

   runs-on: [self-hosted, linux, X64, test-1]

   steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nginxx:latest
    - name: Compose
      run: docker service create --name ngiiinx --publish 80:80 --network appnet --replicas 3 nginxx
